### ISSUE TITLE
Textarea height remains when content is removed

### ISSUE THREAD

**Issue by lynden** [javierjulio/textarea-autosize#10]
When the textarea is filled with content so it expands and then that content is removed the height remains the same.

Is there a setting to drop the textarea back to its min size if there is not enough content to fill it?

Thanks,
Lynden

**Comment by javierjulio** [comment]
Hey @lynden, I'll need more info since this works as expected. Based on your question I'm wondering if you're deleting/updating text programmatically? If so you need to trigger an update, I have a section in the README for that: https://github.com/javierjulio/textarea-autosize#updating-textarea-content Let me know if that solves your issue. Otherwise let me know about how content is being deleted so I can replicate and help you out. Thanks!

**Comment by lynden** [comment]
Hi Javier,

Thanks for getting back to me.

Its based on typing into the textarea to increase the height, then selecting the text within the textarea and deleting it. The textarea height remains the same, is this the expected behaviour?

Thanks,
Lynden

**Comment by javierjulio** [comment]
@lynden no its not, but I can't replicate that. The plugin works as expected when selecting a line or several lines of text and deleting them, the height adjusts. Although keep in mind it won't decrease below the min-height you have set. In the example on the GitHub project page I have a pre-filled textarea that has a minimum height of at least three lines of text (tested there). Give me some more info on what's wrong, perhaps its specific to a browser or some CSS might be off? Any chance you can provide a sample demonstrating the issue? That would be best as I can make a test case for it and make a fix. Let me know so I can help you out. Thanks!

**Comment by sunny04** [comment]
I had the same issue, along with empty scroll-bar appearing on the right when the height was being increased. The problem was solved when I removed the following transition code from my css.

    `transition: 0.3s all;`

So this will apply transition on the height property as well, which is why I think I have having the problem. Not sure if this is a bug or not, but make sure you're not applying transition to 'all' or height, like I was doing.

Good luck.

**Comment by javierjulio** [comment]
@lynden let me know if you're still having trouble. @sunny04 I'll make a note in the README as transitions are not actually supported by the plugin. I knew this developing the plugin and accepted it since I felt a transition was an unnecessary effect. Although there are other plugins that support that feature if its something you require.
