### ISSUE TITLE
irritating resize if you enter the first character

### ISSUE THREAD

**Issue by guettli** [javierjulio/textarea-autosize#12]
There is a small issue: if you enter the first character in an empty textarea an irritating resize
happens.

Is there a way to prevent this?

Despite that little issue, your widgets works very well - thank you.

**Comment by javierjulio** [comment]
@guettli are you able to replicate this on the examples on the gh page site for the plugin? If so, what browser/OS are you using? Do you mean the textarea visually resizes or triggers a resize event but doesn't change visually?

**Comment by guettli** [comment]
No, I can replicate this here http://javierjulio.github.io/textarea-autosize/

In my case the textarea gets a little bit smaller as soon as I enter the first character. Before entering the first char the textarea is empty. After that little resize it works well.

Do you have a hint how to debug this?

**Comment by javierjulio** [comment]
@guettli no because I don't know what browser on what OS you are using to see the bug. Firefox possibly? I can't replicate otherwise. If you can give me more info on when you're seeing the issue I can try to replicate on my end.

**Comment by guettli** [comment]
I am trying to make this reproducible for you. I set up a JSFiddle, but somehow it does not show 
the flicker. 

https://jsfiddle.net/guettli/w12dejhu/

I will leave a new comment, if I am able to reproduce it.

**Comment by guettli** [comment]
@javierjulio I can't reproduce it outside my environment, but inside my environment it still happens.

According to your point of view, is switch to http://www.jacklmoore.com/autosize/ a bad idea?

**Comment by javierjulio** [comment]
@guettli sounds like an issue with your use of the plugin. Have you removed any textarea CSS and only used the bare minimum required by the plugin to see if the issue still persists? **Are you sure you set the correctly caculated min-height on the textarea?** Since you mentioned it shrinks a bit. Are you modifying the textarea with JS at all? Not sure if you might be attaching some events on the textarea and modifying it. You should still be able to customize and interact with the control but if its isolated to your environment that tells me something is causing the issue on your side.

Sure you definitely can use Autosize if you like. Reviewing the code its using the same technique I use here `textarea.scrollHeight` to determine the height. The first version of that plugin used a cloned/ghost element which I didn't like so it was I build this solution.

**Comment by guettli** [comment]
I could not find the bug why the flicker happened. The lib of jacklmoore worked.
Other things are on my todo list now. Thank you for your effort to help me.

**Comment by javierjulio** [comment]
@guettli no problem, happy to help!
