### ISSUE TITLE
Show one line below cursor to tell the user "you have still space"

### ISSUE THREAD

**Issue by guettli** [javierjulio/textarea-autosize#13]
On your example page: http://javierjulio.github.io/textarea-autosize/

If I choose "multiline", and enter

```
1
2
3
4
```

And don't hit ENTER after the number "4". Then the user does not know that the textarea will increase with the next line.

I think it would be a better user experience if autosize would show the user a blank line below the cursor. It should resize more than needed.

Can you follow this idea?

What do you think?

**Comment by alexkravets** [comment]
That means minimal height would be 2 lines. Just a note.

**Comment by guettli** [comment]
@alexkravets yes, this would be the consequence. But for me this would be no drawback. The textarea should have more height than normal (one line) input fields. This gives the user the visual notice: "you can enter several lines here."

**Comment by javierjulio** [comment]
The multiple lines example is simply to demonstrate that you can render the textarea at a height for multiple lines of text initially. Its up to you. I wanted a tool that is configurable through CSS for presentation rather than JS. You can easily determine that minimum height by calculating it from line height and including vertical padding. Thus the single line renders the textarea exactly at a height for a single line of text and expands from there. I don't think extra spacing is necessary. I certainly haven't seen it happen and I like that it just expands after I hit enter or type enough text to move on to a new line. My goal was to keep this very simple and what I felt made the most sense. When I hit enter or keep typing text I always know that the cursor will consistently be at the bottom much like anything else I've used (e.g. Messages in iOS/OSX, Facebook status).

**Comment by javierjulio** [comment]
Thanks all for the input! Closing as I don't see this as necessary or useful but feel free to keep the conversation going.
