### ISSUE TITLE
Is this idempotent?

### ISSUE THREAD

**Issue by inspire22** [javierjulio/textarea-autosize#22]
Instead of calling onload for all textareas, I'd like to load it once when the textarea is first clicked.

But I can't tell how to see if the textarea already has this registered.  Or even if it'd hurt to call it more than once...

**Comment by javierjulio** [comment]
It should be fine to call it more than once since it won't create a new plugin instance if the element already has it in its data https://github.com/javierjulio/textarea-autosize/blob/master/src/jquery.textarea_autosize.js#L46

You should be able to attach a one time listener on any textareas and then in the callback just do `$(this).textareaAutoSize();` assuming `this` is the textarea element in the click event.

If you end up using that way I'd like to see how as I don't have much feedback on how its used other than what I've done.

**Comment by inspire22** [comment]
Working great, thank you :)  I'm just using document.on textarea click to then have it work on any dynamically created textareas.  Overall my goal is to reduce amount of on-ready/on-load code that executes

**Comment by javierjulio** [comment]
Sounds good. That's great, glad its working out! Happy to help.
